### ISSUE TITLE
不要なファイルを消去する

### ISSUE THREAD

**Issue by kn1cht** [LYNCS-Keio/LYNCS-rover#34]
#33 において、`.DS_Store`や`._`で始まるファイルが多数コミットされています。
不要な自動生成ファイルは差分を見づらくするので、消去して`.gitignore`に登録することをお勧めします。

**Comment by ShinMatano** [comment]
アドバイスありがとうございます。修正してみます。

**Comment by naoki-cpp** [comment]
#35 にて対応します。
